plus/my_tour/common2/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from common2 import views

app_name = 'common2'

urlpatterns = [
    # 클래스형 LoginView를 사용
    path('login/', auth_views.LoginView.as_view(
            template_name='common2/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 함수형 view 작성
    path('signup/', views.signup, name='signup')
]

plus/my_tour/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from tour import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),            # http://127.0.0.1:8000/admin
    path('', views.index, name='index'),        # http://127.0.0.1:8000
    path('tour/', include('tour.urls')),      # http://127.0.0.1:8000/board
    path('common2/', include('common2.urls')),  # # http://127.0.0.1:8000/common2
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

plus/my_tour/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'  #  네임 스페이스(소속)

urlpatterns = [

    # path('', views.question_list, name='question_list'), # http://127.0.0.1:8000/board/
    path('index', views.question_list, name='question_list'),
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('answer/create/<int:question_id>/', views.answer_create,
         name='answer_create'),
    # 5장 - 질문 수정 url 매핑 추가
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제 url 매핑 추가
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정/ 삭제 url 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    # 여행지 디테일 페이지
    path('detail/ca/', views.detail_ca, name='detail_ca'),
    path('detail/cj/', views.detail_cj, name='detail_cj'),
    path('detail/gj/', views.detail_gj, name='detail_gj'),
    path('detail/gs/', views.detail_gs, name='detail_gs'),

]

plus/my_tour/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>그린투어</title>

    <link rel="stylesheet" href="{% static 'tour/css/gjstyle.css' %}">
    <link rel="stylesheet" href="{% static 'tour/css/detail.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Single+Day&display=swap" rel="stylesheet">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-round.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2d6623418a.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>

</head>
<body>
<!--내용 start -->
{% block content %}

{% endblock %}
<!--내용 end -->

<!-- 제이쿼리 영역 -->
{% block script %}
<script>
        $("#gotop").click(function () {
          $("html").animate({ scrollTop: 0 }, 800);
        });
</script>
{% endblock %}



</body>
</html>

plus/my_tour/templates/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'tour/css/style.css' %}">
<link rel="stylesheet" href="{% static 'tour/css/head.css' %}">

<div id="footer_part2">
    <!-- 그린투어 로고 -->
    <div class="footer_logo">
        <a href="" id="gotop"><img src="{% static 'tour/images/greeboat.png' %}" alt="그린투어로고"><p>㈜그린투어</p></a>
    </div>
    <br>

    <!-- 회사 정보 -->
    <div class="footer_info">
        <p>그린투어 공동 대표 이사 : 강정현 김민정 성의석 유세현│서울본사 :서울 강남구 테헤란로5길 24, 장연빌딩 3~7층<br>
        사업자 등록번호:000-81-0000│통신판매업신고번호 : 제2010 서울용산 00000호│관광사업등록증번호 : 제0000-000000호 사업자 정보확인<br>
        개인정보보호책임자 : 김학성│상담문의:1253-8282 | FAX : 02-1253-8283~4│보증보험 : 2억6천5백만원 가입<br>
        부득이한 사정에 의해 여행일정이 변경되는 경우 여행자의 사전 동의를 받습니다.</p>
    </div>
    <!--SNS 이미지 링크 연결-->
    <div class="footer_part2_sns">
        <a href="https://ko-kr.facebook.com/" target="_blank"><img src="{% static 'tour/images_min/footer_img/facebook.png' %}" alt="페이스북"></a>
        <a href="https://www.instagram.com/" target="_blank"><img src="{% static 'tour/images_min/footer_img/instagram.png' %}" alt="인스타"></a>
        <a href="https://www.kakaocorp.com/page/" target="_blank"><img src="{% static 'tour/images_min/footer_img/kakao.png' %}" alt="카카오"></a>
        <a href="https://www.youtube.com/" target="_blank"><img src="{% static 'tour/images_min/footer_img/youtube.png' %}" alt="유튜브"></a>
        <a href="https://www.blogger.com/about/?hl=ko" target="_blank"><img src="{% static 'tour/images_min/footer_img/blog.png' %}" alt="블로그"></a>
    </div>
</div>

plus/my_tour/templates/form_errors.html
<!-- 유효성 검사 - 오류 처리 시작-->
{% if form.errors  %}
    <!-- 필드 오류 -->
    {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
        {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
         </div>
        {% endif %}
    {% endfor %}

    <!-- 넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

plus/my_tour/templates/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'tour/css/style.css' %}">
<link rel="stylesheet" href="{% static 'tour/css/head.css' %}">
<script src="{% static 'tour/js/main_js.js' %}"></script>

<div id="container">
    <header>
        <div class="logo">
            <a href="{% url 'index' %}">
                <img src="{% static 'tour/images/greenboat.png' %}" alt="메인" id="logo_pic">
                <h1>
                    <span class="abc">그린</span><span class="cba">투어</span>
                </h1>
            </a>
        </div>
        <input type="checkbox" id="menu-bar">
        <label for="menu-bar">Menu</label>

        <nav class="navbar">
            <ul>
                <li><a href="{% url 'tour:detail_ca' %}">수도권</a></li>
                <li><a href="{% url 'tour:detail_gs' %}">경상권</a></li>
                <li><a href="{% url 'tour:detail_cj' %}">충청/전라권</a></li>
                <li><a href="{% url 'tour:detail_gj' %}">강원/제주권</a></li>
                <li><a href="{% url 'tour:question_list' %}">여행 후기</a></li>

            </ul>
        </nav>
        <div class="smallhead">
            <ul>
                <li>
                    {% if user.is_authenticated %}  <!-- 로그인이 되었다면 -->
                    <a href="{% url 'common2:logout' %}">
                        <span style="font-size: 1.1em; letter-spacing: -1px;">( {{ user.username }} )</span> 로그아웃
                    </a>
                    {% else %}
                    <a href="{% url 'common2:login' %}">
                        {{ user.username }}로그인
                    </a>
                    {% endif %}
                </li>
                <li><a href="{% url 'common2:signup' %}">회원가입</a></li>
                <li><a href="#">도움말</a></li>
                <!--<li>[ <span id="demo"></span> ]</li>-->
            </ul>
        </div>
    </header>
</div>

plus/my_tour/templates/headerXXX.html
{% load static %}
<div id="container">
    <header>
        <div class="smallhead">
            <ul>

                <li>
                    {% if user.is_authenticated %}  <!-- 로그인이 되었다면 -->
                    <a href="{% url 'common2:logout' %}">
                        ( {{ user.username }} )로그아웃
                    </a>
                    {% else %}
                    <a href="{% url 'common2:login' %}">
                        {{ user.username }}로그인
                    </a>
                    {% endif %}
                </li>
                <li><a href="{% url 'common2:signup' %}">회원가입</a></li>
                <li><a href="#">도움말</a></li>
                <li>[ <span id="demo"></span> ]</li>
            </ul>
        </div>
        <div class="mainhead">
            <div class="logo">
<!--                <a href="greentour_index.html"><img src="../static/review/images/greenboat.png" alt="메인" id="logo_pic">-->
                    <a href="">
                        <img src="{% static 'board/images/greenboat.png' %}" alt="메인" id="logo_pic">
                    <h1>
                        그린<span style="color: #444;">투어</span>
                    </h1>
                    </a>
            </div>
            <div class="menu">
                <nav>
                    <ul>
                        <li><a href="">수도권</a></li>
                        <li><a href="">충청/전라권</a></li>
                        <li><a href="">경상권</a></li>
                        <li><a href="">강원/제주권</a></li>
                        <li><a href="">여행후기</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</div>

plus/my_tour/templates/index (1).html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}

<section>
     <div class="main_pic">
            <img src="{% static 'tour/images/sokcho1.jpg' %}" alt="속초사진" id="pic1">
            <img src="{% static 'tour/images/korea.png' %}" alt="대한민국" id="pic2">
    </div>
    <!-- 중간 -->
    <div class="main_box1">
        <h2>그린투어 BEST 추천여행</h2>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}" id="myImage"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
         <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
         <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
    </div>
</section>
        <footer>
            <div>
                <ul id="bottom-menu">
                    <li><a href="#">사이트소개</a></li>
                    <li><a href="#">임원소개</a></li>
                    <li><a href="#"><b>개인정보 처리방침</b></a></li>
                    <li><a href="#">이용약관</a></li>
                    <li><a href="https://gangnam.greenart.co.kr/?cam_idx=1" target="_blank">본사홈페이지</a></li>

                </ul>
            </div>
            <div class="about_us">
                문의) 그린투어 운영팀: help@greentour.com
            </div>
        </footer>

{% endblock %}

plus/my_tour/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'tour/css/indexstyle.css' %}">

<section>
            <div class="main_pic">
                    <img src="{% static 'tour/images/sokcho1.jpg' %}" alt="속초사진" id="pic1">
                    <img src="{% static 'tour/images/korea.png' %}" alt="대한민국" id="pic2">
            </div>
            <!-- 중간 -->
            <div class="main_box1">
                <h2>그린투어 BEST 추천여행</h2>

            <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}" id="myImage"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
         <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
         <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
        <div class="index_box">
            <div class="index_scale">
                <a href="" class="ab_img"><img src="{% static 'tour/images/sokcho1.jpg' %}"></a>
                <p>푸하하하하<i class="fa-regular fa-heart fa-xl"></i><i class="fa-regular fa-map fa-xl"></i></p>
            </div>
        </div>
    </div>
</section>
        <!--<footer>
            <div>
                <ul id="bottom-menu">
                    <li><a href="#">사이트소개</a></li>
                    <li><a href="#">임원소개</a></li>
                    <li><a href="#"><b>개인정보 처리방침</b></a></li>
                    <li><a href="#">이용약관</a></li>
                    <li><a href="https://gangnam.greenart.co.kr/?cam_idx=1" target="_blank">본사홈페이지</a></li>

                </ul>
            </div>
            <div class="about_us">
                문의) 그린투어 운영팀: help@greentour.com
            </div>
        </footer>-->

{% endblock %}

plus/my_tour/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- 왼쪽 그린 로고 -->
        <a class="navbar-brand" href="">그린투어</a>
        <!-- 버튼 -->
        <button class="navbar-toggler" type="button" data-bs-tolle="collapse">
            <span class="navbar-toggler-toggler-icon"></span>
        </button>
        <!-- 로그인 메뉴 -->
        <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}  <!--로그인(인증) 되었다면 -->
                    <a class="nav-link" href="{% url 'common2:logout' %}">
                        {{ user.username }}(로그아웃)
                    </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common2:signin' %}">회원가입</a>
                    {% endif %}
                </li>
                <!--<li class="nav-item">
                    <a class="nav-link" href="">ocr</a>
                </li>-->
            </ul>
        </div>
    </div>
</nav>