plus/plus1/board/board/urls.py
from django.urls import path
from . import views

app_name = 'board'  #  네임 스페이스(소속)

urlpatterns = [
    # http://127.0.0.1:8000/board/
    path('', views.question_list, name='question_list'),
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('answer/create/<int:question_id>/', views.answer_create,
         name='answer_create'),
    # 5장 - 질문 수정 url 매핑 추가
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제 url 매핑 추가
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정/ 삭제 url 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

]

plus/plus1/board/common2/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from common2 import views

app_name = 'common2'

urlpatterns = [
    # 클래스형 LoginView를 사용
    path('login/', auth_views.LoginView.as_view(
            template_name='common2/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 함수형 view 작성
    path('signup/', views.signup, name='signup')
]

plus/plus1/board/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from board import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),            # http://127.0.0.1:8000/admin
    path('', views.index),                      # http://127.0.0.1:8000
    path('board/', include('board.urls')),      # http://127.0.0.1:8000/board
    path('common2/', include('common2.urls')),  # # http://127.0.0.1:8000/common2
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

plus/plus1/config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),            # http://127.0.0.1:8000/admin
    path('', views.index),                      # http://127.0.0.1:8000
    path('board/', include('board.urls')),      # http://127.0.0.1:8000/board
    path('common2/', include('common2.urls')),  # # http://127.0.0.1:8000/common2
]

plus/plus1/board/board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    # objects = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 5장 - DB에서 칼럼에 null 값을 허용한다는 의미, blank=True는 작성 폼에서 form.is_valid() 검사시 값이 없어도 된다는 의미
    modify_date = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/',
                              null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 외래키 제약조건 무시하고 연쇄 삭제됨
    # subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 5장
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

plus/plus1/board/common2/models.py
from django.db import models

# Create your models here.

plus/plus1/board/board/forms.py
from django import forms
from board.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content', 'photo']
        labels = {
            'subject': '제목',
            'content': '내용',
            'photo': '사진'
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용'
        }

plus/plus1/board/common2/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'last_name', 'email']

plus/plus1/board/board/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from datetime import datetime


from board.forms import QuestionForm, AnswerForm
from board.models import Question, Answer


# 홈
def index(request):
    return render(request, 'index.html')
    # return HttpResponse("kang 인덱스") - 테스트용 text

def question_list(request):
    # 질문 답변 게시판
    # question_list = Question.objects.all()
    # return HttpResponse("welcome 안녕")
    # 작성일 기준으로 내림차순 정렬 - -create_date : 작성한 날짜의 역순으로 정렬
    question_list = Question.objects.order_by('-create_date')

    # 페이지 처리
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)    #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'board/question_list.html', context)



def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'board/detail.html', context)


# 질문 등록
@login_required(login_url='common2:login')  # 로그인 필수(세션)
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)  # 가저장
            question.author = request.user
            question.create_date = timezone.now()
            question.save() # 실제 저장
            return redirect('board:question_list')  # index 경로로 이동
    else:   # request.method == "GET"
        form = QuestionForm()
    context = {'form': form}    # context 변수에 딕셔너리 자료 저장
    return render(request, 'board/question_form.html', context)



# 답변 등록
@login_required(login_url='common2:login')  # 로그인 필수(세션)
def answer_create(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) # 폼에 입력된 데이터 전달 받음
        if form.is_valid():
            answer = form.save(commit=False)    # 가저장
            answer.author = request.user        # 4장 41쪽 수정
            answer.question = question          # 외래키 저장
            answer.create_date = timezone.now()
            form.save()   # 실제 저장
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'board/detail.html', context)


# 질문 수정
@login_required(login_url='common2:login') # 오류 나면 login부터 확인 -----------------------
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.author = request.user
            form.save()
            return redirect('board:detail', question_id=question_id)    # 오류 나면 여기도 확인 -----------------------------------
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)


# 답변 수정
@login_required(login_url='common2:login') # 오류 나면 login부터 확인 -----------------------
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.author = request.user
            form.save()
            return redirect('board:detail', question_id=answer.question.id)    # 오류 나면 여기도 확인 -----------------------------------
    else:
        form = AnswerForm(instance=answer)
    context = {'form': form}
    return render(request, 'board/answer_form.html', context)


# 질문 삭제
@login_required(login_url='common2:login')  # 오류 나면 여기 확인 -----------------------------------
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()   # 삭제
    return redirect('board:question_list')


# 답변 삭제
@login_required(login_url='common2:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)

plus/plus1/board/common2/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from common2.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)   #데이터 입력된 폼
        if form.is_valid():
            form.save() #회원 가입 db에 저장
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)    #자동로그인
            return redirect('/')    #index 페이지로 이동
    else:
        form = UserForm()   #빈폼 생성
    context = {'form': form}
    return render(request, 'common2/signup.html', context)

plus/plus1/board/templates/board/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <form method="post">
    {% csrf_token %}
    {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" id="content" name="content"
                rows="10">{{ form.content.value|default_if_none:''}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

plus/plus1/board/templates/board/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ question.subject }}
{% endblock %}
{% block script %}

{% endblock %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <!---->
    <div class="card">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">  <!-- pre-line; 줄바꿈 표시-->
                {{ question.content }}
            </div>
            {% if question.photo %} <!-- 사진이 있다면 -->
            <div class="card-photo">
                <img src="{{ question.photo.url }}">
            </div>
            {% endif %}
            <div class="d-flex justify-content-end">
                <!-- 5장 - 질문 수정일이 있으면 -->
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 mx-2">
                    <div class="mb-2 text-start">수정된 날짜</div>
                    <div>({{ question.modify_date }})</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2">
                    <div class="mb-2 text-start">작성자 : {{ question.author }}</div>
                    <div>{{ question.create_date|date:"Y.m.d H:i:s" }}</div>
                </div>
            </div>
            <!-- 5장 - 수정 버튼 추가 -->
            {% if request.user == question.author %}
            <div>
                <a href="{% url 'board:question_modify' question.id %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <!-- data-uri는 제이쿼리와 연동하는 부분 -->
                <a href=""
                   data-uri="{% url 'board:question_delete' question.id %}"
                    class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>  <!-- 수정: </div> 추가 -->
    <!---->
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    <!---->
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end my-2">
                <!-- 5장 - 답변 수정일이 있으면 -->
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p2 mx-2">
                    <div class="mb-2 text-start">수정된 날짜</div>
                    <div>({{ answer.modify_date|date:"Y.m.d H:i:s" }})</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2">
                    <div class="mb-2 text-start">작성자 : {{ answer.author }}</div>
                    <div>{{ answer.create_date|date:"Y.m.d H:i:s" }}</div>
                </div>
            </div>
            <!-- 5장 - 수정 버튼 추가 -->
            {% if request.user == answer.author %}
            <div>
                <a href="{% url 'board:answer_modify' answer.id %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <!-- data-uri는 제이쿼리와 연동하는 부분 -->
                <a href=""
                   data-uri="{% url 'board:answer_delete' answer.id %}"
                    class="delete btn btn-sm btn-outline-secondary">삭제</a> <!-- 경로 수정해야하나 ? -->
            </div>
            {% endif %}
        </div>
    </div>  <!-- 수정: </div> 추가 -->
    {% endfor %}
    <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 유효성 검사 -->
        {% include 'form_errors.html' %}
        <div class="form-group">
            <textarea name="content" id="content" rows="10" cols="40" class="form-control" style="resize:none;"
                      {% if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
<script>
    $(document).ready(function(){
        $('.delete').click(function(){
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri');  //현재 대상 객체의 주소를 이동
            }
        });
    });
</script>
{% endblock %}

plus/plus1/board/templates/board/question_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>질문 등록</title>
</head>
<body>
  <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
  <form action="" method="post" class="post-form my-3" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- 유효성 검사 - 오류 처리 시작-->
      {% include 'form_errors.html' %}
    <!-- 오류 처리 끝-->
    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" id="subject" name="subject"
             value="{{ form.subject.value|default_if_none:''}}">
              <!-- value - 오류 발생시 입력값이 없는 경우 none을 공백으로 표시하고
                  입력값이 있는 경우 기존값을 유지한다는 의미임 -->
    </div>

    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" id="content" name="content"
                rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>

    <div class="form-group">
      <label for="photo">사진</label>
      <input type="file" id="photo" name="photo">
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</body>
</html>

plus/plus1/board/templates/board/question_list.html
{% extends 'base.html' %}
{% load static %}
{% load board_filter %}
{% block content %}
{% include 'header.html' %}


<div class="container">
    <h1>REVIEW</h1>
    <p>그린 투어와 함께한 후기를 남겨주세요</p>
    <section id="board_main">
        <table class="board_main_table">
            <!-- thead -->
            <thead class="board_table_thd">
                <tr class="tr1">
                    <th>NO</th>
                    <th>제목</th>
                    <th>글쓴이</th>
                    <th>작성일</th>
                </tr>
            </thead>
            <!-- tbody -->
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                <tr class="tr2">
                    <!--<td>{{ forloop.counter }}</td>-->  <!-- 1번 부터 시작 -->
                    <!-- 템플릿 태그 -->
                    <!-- 1페이지 13~4, 2페이지 3~1 (최신글이 1페이지로)
                        13 - 1(시작인덱스1, 11, 21) - (0~9:현재 인덱스) + 1 = 13 >> 공식
                    -->
                    <!-- 제목 -->
                    <td> {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }} </td>
                    <td>
                        <a href="{% url 'board:detail' question.id %}">
                            {{ question.subject }}
                        </a>
                        <!-- 댓글이 있을때 제목 옆에 표시하는 기능 -->
                        {% if question.answer_set.count > 0 %}
                            <span class="text-danger">[{{ question.answer_set.count }}]</span>
                        {% endif %}
                    </td>
                    <!-- 글쓴이 -->
                    <td>{{ question.author }}</td>
                    <!-- 작성 일시 -->
                    <td>{{ question.create_date|date:"Y.m.d H:i:s" }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <p>질문이 없습니다.</p>
            {% endif %}
            </tbody>
        </table>

        <!-- 페이지 처리 영역 -->
        <ul class="pagination">
            <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item-disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
            {% endif %}

            <!-- 현재 페이지-->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number == question_list.number %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">&raquo;</a>
                </li>
            {% else %}
                <li class="page-item-disabled">
                    <a class="page-link" href="">&raquo;</a>
                </li>
            {% endif %}
        </ul>
        <a href="{% url 'board:question_create' %}"
           class="board_main_q_btn">질문 등록</a>
    </section>
</div>
{% endblock %}

plus/plus1/board/templates/board/question_list2.html
{% extends 'base.html' %}
{% load static %}
{% load board_filter %}
{% block content %}
{% include 'header.html' %}


<div class="container">
    <h1>REVIEW</h1>
    <p>그린 투어와 함께한 후기를 남겨주세요</p>
    <section id="board_main">
        <table class="board_main_table">
            <!-- thead -->
            <thead class="board_table_thd">
                <tr>
                    <th>NO</th>
                    <th>제목</th>
                    <th>글쓴이</th>
                    <th>작성일</th>
                </tr>
            </thead>
            <!-- tbody -->
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                <tr>
                    <!--<td>{{ forloop.counter }}</td>-->  <!-- 1번 부터 시작 -->
                    <!-- 템플릿 태그 -->
                    <!-- 1페이지 13~4, 2페이지 3~1 (최신글이 1페이지로)
                        13 - 1(시작인덱스1, 11, 21) - (0~9:현재 인덱스) + 1 = 13 >> 공식
                    -->
                    <!-- 제목 -->
                    <td> {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }} </td>
                    <td>
                        <a href="{% url 'board:detail' question.id %}">
                            {{ question.subject }}
                        </a>
                        <!-- 댓글이 있을때 제목 옆에 표시하는 기능 -->
                        {% if question.answer_set.count > 0 %}
                            <span class="text-danger">[{{ question.answer_set.count }}]</span>
                        {% endif %}
                    </td>
                    <!-- 글쓴이 -->
                    <td>{{ question.author }}</td>
                    <!-- 작성 일시 -->
                    <td>{{ question.create_date|date:"Y.m.d H:i:s" }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <p>질문이 없습니다.</p>
            {% endif %}
            </tbody>
        </table>

        <!-- 페이지 처리 영역 -->
        <ul class="pagination">
            <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item-disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
            {% endif %}

            <!-- 현재 페이지-->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number == question_list.number %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">&raquo;</a>
                </li>
            {% else %}
                <li class="page-item-disabled">
                    <a class="page-link" href="">&raquo;</a>
                </li>
            {% endif %}
        </ul>
        <a href="{% url 'board:question_create' %}"
           class="board_main_q_btn">질문 등록</a>
    </section>
</div>
{% endblock %}