plus/my_tour/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from tour import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),            # http://127.0.0.1:8000/admin
    path('', views.index, name='index'),        # http://127.0.0.1:8000
    path('tour/', include('tour.urls')),      # http://127.0.0.1:8000/board
    path('common2/', include('common2.urls')),  # # http://127.0.0.1:8000/common2
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

plus/my_tour/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'  #  네임 스페이스(소속)

urlpatterns = [

    # path('', views.question_list, name='question_list'), # http://127.0.0.1:8000/board/
    path('index', views.question_list, name='question_list'),
    path('detail/<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('answer/create/<int:question_id>/', views.answer_create,
         name='answer_create'),
    # 5장 - 질문 수정 url 매핑 추가
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제 url 매핑 추가
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정/ 삭제 url 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),

    # 여행지 디테일 페이지
    path('detail/ca/', views.detail_ca, name='detail_ca'),
    path('detail/cj/', views.detail_cj, name='detail_cj'),
    path('detail/gj/', views.detail_gj, name='detail_gj'),
    path('detail/gs/', views.detail_gs, name='detail_gs'),

]

plus/my_tour/tour/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    # objects = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 5장 - DB에서 칼럼에 null 값을 허용한다는 의미, blank=True는 작성 폼에서 form.is_valid() 검사시 값이 없어도 된다는 의미
    modify_date = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to='tour/images/%Y/%m/%d/',
                              null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 외래키 제약조건 무시하고 연쇄 삭제됨
    # subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # 5장
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

plus/my_tour/tour/forms.py
from django import forms
from tour.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content', 'photo']
        labels = {
            'subject': '제목',
            'content': '내용',
            'photo': '사진'
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {

            'content': '답변내용'
        }

plus/my_tour/tour/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from datetime import datetime


from tour.forms import QuestionForm, AnswerForm
from tour.models import Question, Answer


# 홈
def index(request):
    return render(request, 'index.html')
    # return HttpResponse("kang 인덱스") - 테스트용 text

# 정보페이지로 이동 - 수도권
def detail_ca(request):
    return render(request, 'tour/detail_ca.html')

# 정보페이지로 이동 - 충청/전라도
def detail_cj(request):
    return render(request, 'tour/detail_cj.html')

# 정보페이지로 이동 - 강원/제주도
def detail_gj(request):
    return render(request, 'tour/detail_gj.html')

# 정보페이지로 이동 - 경상도
def detail_gs(request):
    return render(request, 'tour/detail_gs.html')

# 정보페이지로 이동 - 수도권

# 리뷰 게시판
def question_list(request):
    # question_list = Question.objects.all()
    # return HttpResponse("welcome 안녕")
    # 작성일 기준으로 내림차순 정렬 - -create_date : 작성한 날짜의 역순으로 정렬
    question_list = Question.objects.order_by('-create_date')

    # 페이지 처리
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)    #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'tour/question_list.html', context)


def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'tour/detail.html', context)


# 리뷰 등록
@login_required(login_url='common2:login')  # 로그인 필수(세션)
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)  # 가저장
            question.author = request.user
            question.create_date = timezone.now()
            question.save() # 실제 저장
            return redirect('tour:question_list')  # index 경로로 이동
    else:   # request.method == "GET"
        form = QuestionForm()
    context = {'form': form}    # context 변수에 딕셔너리 자료 저장
    return render(request, 'tour/question_form.html', context)



# 답변 등록
@login_required(login_url='common2:login')  # 로그인 필수(세션)
def answer_create(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST) # 폼에 입력된 데이터 전달 받음
        if form.is_valid():
            answer = form.save(commit=False)    # 가저장
            answer.author = request.user        # 4장 41쪽 수정
            answer.question = question          # 외래키 저장
            answer.create_date = timezone.now()
            form.save()   # 실제 저장
            return redirect('tour:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'tour/detail.html', context)


# 질문 수정
@login_required(login_url='common2:login') # 오류 나면 login부터 확인 -----------------------
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.author = request.user
            form.save()
            return redirect('tour:detail', question_id=question_id)    # 오류 나면 여기도 확인 -----------------------------------
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'tour/question_form2.html', context)


# 답변 수정
@login_required(login_url='common2:login') # 오류 나면 login부터 확인 -----------------------
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.author = request.user
            form.save()
            return redirect('tour:detail', question_id=answer.question.id)    # 오류 나면 여기도 확인 -----------------------------------
    else:
        form = AnswerForm(instance=answer)
    context = {'form': form}
    return render(request, 'tour/answer_form.html', context)


# 질문 삭제
@login_required(login_url='common2:login')  # 오류 나면 여기 확인 -----------------------------------
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()   # 삭제
    return redirect('tour:question_list')


# 답변 삭제
@login_required(login_url='common2:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('tour:detail', question_id=answer.question.id)

plus/my_tour/templates/tour/백업/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'tour/css/boardDetail.css' %}">
<!--=========== confirm or alert 구현 수정 필요 ===========-->
<!--=========== 질문자 구간 ===========-->
<div class="board_detail_container">
    <!--=========== 질문자 제목 ===========-->
    <h2 class="board_detail_subject">{{ question.subject }}</h2>

    <div class="board_detail_part1">
        <div class="board_detail_content_part1_all">
            <!--=========== 질문자 내용 ===========-->
            <div class="board_detail_content">
                {{ question.content }}
            </div>
            <!-- 사진이 있다면 -->
            {% if question.photo %}
            <div class="photo">
                <img src="{{ question.photo.url }}">
            </div>
            {% endif %}

            <!--=========== 질문자 ID/수정일 text ===========-->
            <div class="board_detail_author_date_all">
                <!-- 5장 - 질문 수정일이 있으면 -->
                {% if question.modify_date %}
                <div class="board_detail_modify_date_all">
                    <div class="board_detail_modify_date_text">수정일</div>
                    <div class="board_detail_modify_date">{{ question.modify_date|date:"Y.m.d H:i:s" }}</div>
                </div>
                {% endif %}
                <div class="board_detail_author_create_date">
                    <div class="board_detail_author">{{ question.author }}</div>
                    <div class="board_detail_create_date">{{ question.create_date|date:"Y.m.d H:i:s" }}</div>
                </div>
            </div>
            <!--=========== 질문자 수정/삭제 버튼 ===========-->
            {% if question.author == request.user %}
            <div class="board_detail_correction_delete_button1">
                <div class="board_detail_correction_button1_box">
                    <a href="{% url 'tour:question_modify' question.id %}"
                        class="board_detail_correction_button1">수정</a>
                </div>
                <!-- data-uri는 제이쿼리와 연동하는 부분 -->
                <div class="board_detail_delete_button1_box">
                    <a href="{% url 'tour:question_delete' question.id %}"
                   data-uri=""
                        class="delete board_detail_delete_button1">삭제</a>
                    <!-- 글삭제에서 uri를 걸어버리면 question.id 를 지우긴하지만 찾아갈 넘버를 못찾음 -->
                </div>
            </div>
            {% endif %}
        </div>
    </div>  <!-- 수정: </div> 추가 -->

    <!--<div class="board_detail_question_answer_box">
        <h5 class="board_detail_question_answer">
            {{ question.answer_set.count }}개의 답변이 있습니다.
        </h5>
    </div>-->

    <!--=========== 답변자 구간 ===========-->
    {% for answer in question.answer_set.all %}
    <div class="board_detail_answer_part2">
        <div class="board_detail_content_answer_part2_all">
            <!--=========== 답변자 댓글 ===========-->
            <div class="board_detail_answer_content">
                {{ answer.content }}
            </div>

            <div class="board_detail_answer_author_date_all1">
                <!--=========== 답변자 ID/수정일 text ===========-->
                {% if answer.modify_date %}
                <div class="board_detail_answer_modify_text_date">
                    <div class="board_detail_answer_modify_date_text">수정일</div>
                    <div class="board_detail_answer_modify_date">{{ answer.modify_date|date:"Y.m.d H:i:s" }}</div>
                </div>
                {% endif %}
                <div class="board_detail_answer_author_create_date">
                    <div class="board_detail_answer_author">{{ answer.author }}</div>
                    <div class="board_detail_answer_create_date">{{ answer.create_date|date:"Y.m.d H:i:s" }}</div>
                </div>
            </div>
            <!--=========== 답변자 수정/삭제 버튼 ===========-->
            {% if answer.author == request.user %}
            <div class="board_detail_correction_delete_button2">
                <div class="board_detail_correction_button2_box">
                    <a href="{% url 'tour:answer_modify' answer.id %}"
                        class="board_detail_correction_button2">수정</a>
                </div>
                <!-- data-uri는 제이쿼리와 연동하는 부분 -->
                <div class="board_detail_delete_button2_box">
                    <a href="#"
                       data-uri="{% url 'tour:answer_delete' answer.id %}"
                       class="delete board_detail_delete_button2">삭제</a> <!-- 경로 수정해야하나 ? -->
                </div>
            </div>
            {% endif %}
        </div>
    </div>  <!-- 수정: </div> 추가 -->
    {% endfor %}
    <!--=========== 답변자 textarea / 등록 버튼 ===========-->
    <form action="{% url 'tour:answer_create' question.id %}" method="post" class="board_detail_textarea_form">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <!--=========== 답변자 textarea ===========-->
        <div class="board_detail_textarea_box">
            <textarea name="content" id="content" rows="10" cols="40" class="board_detail_textarea"
                      {% if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <!--=========== 답변자 등록 버튼 ===========-->
        <input type="submit" value="답변 등록" class="board_detail_input_button">
    </form>
    <!--=========== 목록 버튼 ===========-->
    <button type="button" class="board_detail_button" onclick="location.href='{% url 'tour:question_list' %}'">목록</button>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('.delete').click(function(){
            if(confirm('정말 삭제하시겠습니까?')){
                location.href=$(this).data('uri');  //현재 대상 객체의 주소를 이동
            }
        });
    });
</script>
{% endblock %}