plus/min_project/board/common2/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from common2 import views

app_name = 'common2'

urlpatterns = [
    # 클래스형 LoginView를 사용
    path('login/', auth_views.LoginView.as_view(
            template_name='common2/login.html'), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 함수형 view 작성
    path('signup/', views.signup, name='signup')
]

plus/min_project/board/common2/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from common2.forms import UserForm


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        #로그인
        user = authenticate(username=username, password=password)

        if user is not None:        # user가 있으면
            login(request, user)    # 로그인
            return redirect('/')
        else:
            error = "아이디와 비밀번호를 확인해 주세요"
            context = {'error': error}
            return render(request, 'common2/signin.html', context)
    else:
        return render(request, 'common2/signin.html')

def signout(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save() # 회원 가입 저장
            # 가입 후 자동 로그인
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'common2/signup.html', context)


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save() #회원 가입 저장
            # 가입후 자동 로그인
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'common2/signup.html', context)

plus/min_project/board/templates/from_errors.html
<!-- 유효성 검사 - 오류 처리 시작-->
{% if form.errors  %}
    <!-- 필드 오류 -->
    {% for field in form %}  <!-- 폼을 필드를 순회하면서 -->
        {% if field.errors  %} <!-- 필드에 오류가 있으면 -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ field.errors }}  <!-- 에러 출력 -->
         </div>
        {% endif %}
    {% endfor %}

    <!-- 넌 필드 오류-->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- 오류 처리 끝-->

plus/min_project/board/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- 왼쪽 그린 로고 -->
        <a class="navbar-brand" href="#">그린투어</a>
        <!-- 버튼 -->
        <button class="navbar-toggler" type="button" data-bs-tolle="collapse">
            <span class="navbar-toggler-toggler-icon"></span>
        </button>
        <!-- 로그인 메뉴 -->
        <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}  <!--로그인(인증) 되었다면 -->
                    <a class="nav-link" href="{% url 'common2:logout' %}">
                        {{ user.username }}(로그아웃)
                    </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common2:signin' %}">회원가입</a>
                    {% endif %}
                </li>
                <!--<li class="nav-item">
                    <a class="nav-link" href="">ocr</a>
                </li>-->
            </ul>
        </div>
    </div>
</nav>